# Generated by Django 4.1 on 2022-08-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_crypto'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='qr_code',
            field=models.TextField(default='Value'),
            preserve_default=False,
        ),
    ]
